#!/bin/bash
##
# Start magento
# Run this when ever you are ready to use the box
##
echo "Removing existing news application"
docker rm -f service >/dev/null

echo "Starting service application"

echo "Executing : docker run -d -p 1011:80 -v \$(pwd)/www:/var/www --name news zend web"
docker run -d -p 1013:80 -v $(pwd)/www:/var/www --name service user web >/dev/null

echo "Load http://192.168.99.100:1013"